export const REQUEST_GIFS = 'REQUEST_GIFS';
export const RECEIVE_GIFS = 'RECEIVE_GIFS';
export const REQUEST_MORE_GIFS = 'REQUEST_MORE_GIFS';
export const RECEIVE_MORE_GIFS = 'RECEIVE_MORE_GIFS';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
export const SET_QUERY = 'SET_QUERY';
