export const REQUEST_TRENDING_GIFS = 'REQUEST_TRENDING_GIFS';
export const RECEIVE_TRENDING_GIFS = 'RECEIVE_TRENDING_GIFS';
export const REQUEST_MORE_GIFS = 'REQUEST_MORE_GIFS';
export const RECEIVE_MORE_GIFS = 'RECEIVE_MORE_GIFS';
export const REQUEST_SEARCHED_GIFS = 'REQUEST_SEARCHED_GIFS';
export const RECEIVE_SEARCHED_GIFS = 'RECEIVE_SEARCHED_GIFS';
export const CHANGE_OFFSET = 'CHANGE_OFFSET';
